export enum SATIETY {
  SATIETY_SET_FEED = 100,
  MIN_SATIETY = 0,
  MAX_SATIETY = 100,
  DEFAULT_SATIETY = 100,
}

export enum CLEANLINESS {
  CLEANLINESS_PER_CLEAN = 100,
  MIN_CLEANLINESS = 0,
  MAX_CLEANLINESS = 100,
  DEFAULT_CLEANLINESS = 100,
}

export enum MBTIENUM {  
  MIN_MBTI = 0,
  MAX_MBTI = 100,
  DEFAULT_MBTI = 50,
}
