export enum SATIETY {
  SATIETY_PER_FEED = 10,
  MIN_SATIETY = 0,
  MAX_SATIETY = 100,
  DEFAULT_SATIETY = 100,
}

export enum CLEANLINESS {
  CLEANLINESS_PER_FEED = 10,
  MIN_CLEANLINESS = 0,
  MAX_CLEANLINESS = 100,
  DEFAULT_CLEANLINESS = 100,
}
